In [2]:
import numpy as np

In [3]:
list=[1,2,3,4,5]
print(type(list))

<class 'list'>


In [10]:
list=[1,2,3,4,5]
print(type(list))
print(type(np.array(list)))
arr1=np.array(list)
print(arr1)
print(list)
arr1[0]
list[0]
np.array(list)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4 5]
[1, 2, 3, 4, 5]


array([1, 2, 3, 4, 5])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros(4)

array([0., 0., 0., 0.])

In [16]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones((6,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [79]:
np.random.randint(0,100)

65

In [80]:
np.random.randint(0,100,4)

array([62, 23, 80, 68])

In [81]:
np.random.randint(0,100,(2,5))

array([[94, 12, 16, 52, 55],
       [24, 35, 13, 50, 49]])

In [82]:
np.random.randint(0,100,(7,7))

array([[39, 93, 54, 19, 43, 90, 33],
       [ 1,  9,  8, 29, 57, 47, 96],
       [22,  7,  1, 50, 60, 92, 97],
       [52, 55, 21, 25, 65, 83, 95],
       [86, 45, 74, 68, 78,  9, 61],
       [78, 67, 66, 12, 99, 51, 56],
       [95, 11, 81, 42, 91, 84, 94]])

In [139]:
np.random.seed(62)
np.random.randint(0,513)

24

In [144]:
np.random.seed(58)
arr=np.random.randint(1,100,(5,5))
arr

array([[36, 33, 24, 26, 15],
       [22, 36, 26, 34, 91],
       [38,  1, 85, 63, 67],
       [ 1,  4, 47, 13, 53],
       [73, 50, 39, 30, 95]])

In [156]:
arr.max()
arr.min()
arr.mean()
arr.argmax()
arr.argmin()

11

In [159]:
arr.reshape(2,15)

ValueError: cannot reshape array of size 25 into shape (2,15)

In [160]:
arr.reshape(1,25)

array([[36, 33, 24, 26, 15, 22, 36, 26, 34, 91, 38,  1, 85, 63, 67,  1,
         4, 47, 13, 53, 73, 50, 39, 30, 95]])

In [164]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [166]:
mat[2,2]

22

In [167]:
mat[0,:]#row extraction

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [169]:
mat[:,0]#column extraction

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Now extracting a perticular dimension matrix

In [170]:
mat[3:6,3:6]

array([[33, 34, 35],
       [43, 44, 45],
       [53, 54, 55]])